# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: PHP Boy Scout
subtitle: Always leave the codebase better than you found it
email: matt@phpboyscout.uk
url-pretty: "phpboyscout.uk"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://phpboyscout.uk" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  phpboyscout

# Build settings
#theme: monophase
remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/images/7816e69efe1094de25f347be8f20d6e0.jpg"
round-avatar: true

social-network-links:
  email: "matt@phpboyscout.uk"
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  github: phpboyscout

# Add a search button to the navbar
post_search: true

# Add a button in the footer to edit the current page. Only works if your website is hosted on GitHub
edit_page_button: true

timezone: "Europe/London"
markdown: kramdown
highlighter: rouge
# permalink: /:year-:month-:day-:title.html
paginate: 5

kramdown:
  input: GFM



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
