# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: PHP Boy Scout
subtitle: Always leave the codebase better than you found it
email: matt@phpboyscout.uk
url-pretty: "phpboyscout.uk"
author: Matt Cockayne
baseurl: ""
url: "https://phpboyscout.uk"
github_username:  phpboyscout
remote_theme: daattali/beautiful-jekyll@6.0.1
avatar: "/assets/images/7816e69efe1094de25f347be8f20d6e0.jpg"
round-avatar: true
post_search: true
edit_page_button: true
timezone: "Europe/London"
markdown: kramdown
highlighter: rouge
paginate: 5
kramdown:
  input: GFM
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
social-network-links:
  email: "matt@phpboyscout.uk"
  rss: true
  github: phpboyscout
